### ISSUE TITLE
Items scroll to the top of window when a new damage formula is added, if they have an activation cost

### ISSUE THREAD

**Issue by etiquettestartshere** [krbz999/dicerecharge#17]
Currently, when an item has an Activation Cost (like `1` `Action`), adding a new Damage Formula (hitting the ➕), or hitting enter or clicking off the input field after entering a new formula, scrolls the item's window to the top. This only happens with an activation cost (though that cost can be the `None` option), but if that field is left blank, it does not seem to occur. 

This is kind of a hard one to explain the specifics of, as I'm not entirely sure what's happening, but that's my best explanation. It's possible I entirely misunderstood what is going on here. It may happen in other instances I didn't find.

These results were produced in dnd5e 2.4.0, foundry v11.315, no modules other than Dice Recharge were enabled. Included is a video of the behavior: 

https://github.com/krbz999/dicerecharge/assets/148253744/9ef283d7-3130-41ec-afe8-b96ab83be3d2

**Comment by krbz999** [comment]
Seems like the sheet calling `setPosition` removes all saved scroll positions. The same happens when you simply move the sheet around. Might not strictly be a bug with Dice Recharge, but my calling `setPosition` is far from necessary.
