### ISSUE TITLE
v10: Add a setting to configure how many times recharge formulas should be upscaled when using Gritty Realism

### ISSUE THREAD

**Issue by GMFish** [krbz999/dicerecharge#5]
When using the Gritty Realism rest variant, the mod only uses recharge formula's once instead of 7 times upon a long rest.

**Comment by krbz999** [comment]
The v10 release of the module will include a setting for the GM to define upscaling of recovery formulas when Gritty Realism is enabled and an actor takes a long rest (not a short rest).
- This means you can set the value to 7 and an item that would roll '1d4 + 1' will roll '7d4 + 7', etc.
