### ISSUE TITLE
Add support for "Once you use this feature roll a 1dX" items

### ISSUE THREAD

**Issue by fotoply** [krbz999/dicerecharge#7]
Quite a lot of homebrew items use a system where a feature can be used until a specific value (or lower) is rolled on a die.

Currently this is not possible in Foundry, but your module seems like it would be the perfect fit for it.

**Comment by krbz999** [comment]
Do you have an example of this

**Comment by fotoply** [comment]
Here is an example from a Loot Tavern item
![image](https://user-images.githubusercontent.com/446006/187296084-46b6d076-09ce-444a-8c68-29c02e727ee0.png)

**Comment by krbz999** [comment]
So two things:
- Disabling or changing functionality of an item is not within the scope of this module.
- What would having the module roll a die accomplish that putting '1d6' in the `Other Formula` field does not?

**Comment by krbz999** [comment]
This has been implemented in the v10 version of the module. You can enter a formula that an item should roll to regain when reaching zero limited uses (equal to or higher). For example, _staff of the magi_ which regains 1d12+1 charges if you roll a 20 on a d20 when it reaches zero charges.

**Comment by fotoply** [comment]
Oh, nice, thats exactly what was needed 👍 

Was not clear from the README that it was already possible, but good to know

**Comment by krbz999** [comment]
It is on the v10 branch.
https://github.com/krbz999/dicerecharge/tree/v10
